# Generated by Django 5.0.6 on 2024-07-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingprogress',
            name='data',
        ),
        migrations.AddField(
            model_name='scrapingprogress',
            name='step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapingprogress',
            name='total_steps',
            field=models.IntegerField(default=0),
        ),
    ]
