# Generated by Django 5.0.6 on 2024-07-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0003_scrapingprogress_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('img_url', models.URLField(max_length=2048)),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
    ]
