# Generated by Django 5.0.6 on 2024-07-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraperapp.company'),
        ),
    ]
